'bootstrap_errors_list:  
test aniso_magic.py: program produced incorrect output.  
Traceback below: 
  File "/Users/nebula/Python/Basic_input_output/error_logging.py", line 28, in go_through
    i()
  File "Bootstrap.py", line 62, in complete_aniso_magic_test
    check_bootstrap(output2, aniso_magic_reference)
  File "Bootstrap.py", line 36, in check_bootstrap
    raise ValueError("program produced incorrect output")

test watsonsV.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Basic_input_output/error_logging.py", line 28, in go_through
  File "Bootstrap.py", line 142, in complete_watsonsV_test
    output1 = do_watsonsV()
  File "Bootstrap.py", line 130, in do_watsonsV
    obj = env.run("watsonsV.py", "-v", watsonsV_infile, "-f2", watsonsV_infile2, stdin='q') # messed up on purpose, for testing
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)


'rename_me_errors_list:  
test angle.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 241, in complete_angle_test
    angle.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test zeq.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 266, in complete_zeq_test
    zeq.plot_program_sequence(stdout=True)
  File "Rename_me.py", line 187, in plot_program_sequence
    result = self.run_program()
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test di_eq.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 289, in complete_di_eq_test
    di_eq.list_sequence()
  File "Rename_me.py", line 195, in list_sequence
    result = self.run_program(output_type = "stdout")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test azdip_magic.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 303, in complete_azdip_magic_test
    azdip_magic.run_program()
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test combine_magic_test.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 316, in complete_combine_magic_test
    obj = env.run('combine_magic.py', '-WD', directory, '-F', output_file, '-f', input_1, input_2)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test customize_criteria.py: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/customize_criteria_outfile.out'.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 389, in complete_customize_criteria_test
    customize_criteria.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 179, in file_in_file_out_sequence
    self.check_file_output(result, self.ref_out)
  File "Rename_me.py", line 144, in check_file_output
    parsed_output = PT.file_parse_by_word_and_pmagpy_strip(output_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 97, in file_parse_by_word_and_pmagpy_strip
    data = file_parse_by_word(a_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 71, in file_parse_by_word
    data = open(the_file, 'rU').readlines()

test download_magic.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 348, in complete_download_magic_test
    output = str(download_magic.run_program()).split()
  File "Rename_me.py", line 77, in run_program
    obj = env.run(self.name, '-WD', directory, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test dipole_pinc.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 399, in complete_dipole_pinc_test
    dipole_pinc.list_sequence()
  File "Rename_me.py", line 195, in list_sequence
    result = self.run_program(output_type = "stdout")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test dipole_plat.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 408, in complete_dipole_plat_test
    dipole_plat.list_sequence()
  File "Rename_me.py", line 195, in list_sequence
    result = self.run_program(output_type = "stdout")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test grab_magic_key.py: Wrong output.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 421, in complete_grab_magic_key_test
    grab_magic_key.list_sequence()
  File "Rename_me.py", line 198, in list_sequence
    self.check_list_output(new_list, self.ref_out)
  File "Rename_me.py", line 135, in check_list_output
    raise NameError("Wrong output")

test incfish.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 431, in complete_incfish_test
    incfish.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test magic_select.py: [Errno 2] No such file or directory: 'magic_select_results_new.out'.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 440, in complete_magic_select_test
    magic_select.file_in_file_out_sequence()
  File "Rename_me.py", line 179, in file_in_file_out_sequence
    self.check_file_output(result, self.ref_out)
  File "Rename_me.py", line 144, in check_file_output
    parsed_output = PT.file_parse_by_word_and_pmagpy_strip(output_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 97, in file_parse_by_word_and_pmagpy_strip
    data = file_parse_by_word(a_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 71, in file_parse_by_word
    data = open(the_file, 'rU').readlines()

test nrm_specimens_magic.py: nrm_specimens_magic.py encountered an invalid file.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 454, in complete_nrm_specimens_magic_test
    nrm_specimens_magic.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 84, in run_program
    raise NameError(str(self.name) + " encountered an invalid file")

test sundec.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 464, in complete_sundec_test
    sundec.run_program()
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test pca_example.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 476, in complete_pca_test
    pca.list_sequence()
  File "Rename_me.py", line 195, in list_sequence
    result = self.run_program(output_type = "stdout")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test scalc.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 488, in complete_scalc_test
    scalc.list_sequence()
  File "Rename_me.py", line 195, in list_sequence
    result = self.run_program(output_type = "stdout")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test scalc_magic.py: Wrong output.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 521, in complete_scalc_magic_test
    scalc_magic.list_sequence()
  File "Rename_me.py", line 198, in list_sequence
    self.check_list_output(new_list, self.ref_out)
  File "Rename_me.py", line 135, in check_list_output
    raise NameError("Wrong output")

test vgp_di.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 547, in complete_vgp_di_test
    vgp_di.list_sequence()
  File "Rename_me.py", line 195, in list_sequence
    result = self.run_program(output_type = "stdout")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test_watsonsF.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 558, in complete_watsonsF_test
    watsonsF.list_sequence()
  File "Rename_me.py", line 195, in list_sequence
    result = self.run_program(output_type = "stdout")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test apwp.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 565, in complete_apwp_test
    apwp.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test b_vdm.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 570, in complete_b_vdm_test
    b_vdm.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test cart_dir.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 575, in complete_cart_dir_test
    cart_dir.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test convert_samples.py: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/convert_samples_Northern_Iceland.txt'.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 580, in complete_convert_samples_test
    convert_samples.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 179, in file_in_file_out_sequence
    self.check_file_output(result, self.ref_out)
  File "Rename_me.py", line 144, in check_file_output
    parsed_output = PT.file_parse_by_word_and_pmagpy_strip(output_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 97, in file_parse_by_word_and_pmagpy_strip
    data = file_parse_by_word(a_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 71, in file_parse_by_word
    data = open(the_file, 'rU').readlines()

test di_geo.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 585, in complete_di_geo_test
    di_geo.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test di_tilt.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 590, in complete_di_tilt_test
    di_tilt.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test dir_cart.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 595, in complete_dir_cart_test
    dir_cart.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test di_rot.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 600, in complete_di_rot_test
    di_rot.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test di_vgp.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 605, in complete_di_vgp_test
    di_vgp.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test eigs_s.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 610, in complete_eigs_s_test
    eigs_s.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test eq_di.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 615, in complete_eq_di_test
    eq_di.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test gobing.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 620, in complete_gobing_test
    gobing.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test gofish.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 625, in complete_gofish_test
    gofish.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test gokent.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 630, in complete_gokent_test
    gokent.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test go_princ.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 636, in complete_goprinc_test
    goprinc.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test igrf.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 642, in complete_igrf_test
    igrf.file_in_file_out_sequence(interactive=True)
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test k15.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Rename_me.py", line 649, in complete_k15_s_test
    k15_s.file_in_file_out_sequence()
  File "Rename_me.py", line 178, in file_in_file_out_sequence
    result = self.run_program(output_type = "file")
  File "Rename_me.py", line 81, in run_program
    obj = env.run(self.name, '-f', self.infile, '-F', self.outfile, self.arg_0, self.arg_1, self.arg_2, self.arg_3, self.arg_4, self.arg_5, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

'random_errors_list:  
test gaussian.py: global name 'o1' is not defined.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Random.py", line 186, in complete_gaussian_test
    print("output 1 length: ", o1)

test fisher.py: fisher.py is producing the wrong amount of output.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Random.py", line 36, in complete_fisher_test
    raise NameError("fisher.py is producing the wrong amount of output")

test tk03.py: cannot concatenate 'str' and 'list' objects.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Random.py", line 120, in complete_tk03_test
    print "output1: " + out1


'extra_output_errors_list:  
testing aarm_magic.py: [Errno 2] No such file or directory: 'aarm_magic_anisotropy_new.out'.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Extra_output.py", line 198, in complete_aarm_magic_test
    aarm_magic.ex_out_sequence()
  File "Extra_output.py", line 123, in ex_out_sequence
    self.standard_check_file_sequence()
  File "Extra_output.py", line 128, in standard_check_file_sequence
    self.check_file_output(self.outfile1, self.correctfile1, reference="correct")
  File "Extra_output.py", line 111, in check_file_output
    out = PT.file_parse_by_word_and_pmagpy_strip(outfile)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 97, in file_parse_by_word_and_pmagpy_strip
    data = file_parse_by_word(a_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 71, in file_parse_by_word
    data = open(the_file, 'rU').readlines()

test atrm_magic.py: [Errno 2] No such file or directory: 'atrm_anisotropy_new.out'.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Extra_output.py", line 211, in complete_atrm_magic_test
    atrm.ex_out_sequence()
  File "Extra_output.py", line 123, in ex_out_sequence
    self.standard_check_file_sequence()
  File "Extra_output.py", line 128, in standard_check_file_sequence
    self.check_file_output(self.outfile1, self.correctfile1, reference="correct")
  File "Extra_output.py", line 111, in check_file_output
    out = PT.file_parse_by_word_and_pmagpy_strip(outfile)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 97, in file_parse_by_word_and_pmagpy_strip
    data = file_parse_by_word(a_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 71, in file_parse_by_word
    data = open(the_file, 'rU').readlines()

test hysteresis_magic.py: [Errno 2] No such file or directory: 'hysteresis_magic_rmag_new.out'.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Extra_output.py", line 238, in complete_hysteresis_magic_test
    hysteresis_magic.ex_out_sequence() # this re runs hysteresis magic, but that is not a problem
  File "Extra_output.py", line 123, in ex_out_sequence
    self.standard_check_file_sequence()
  File "Extra_output.py", line 128, in standard_check_file_sequence
    self.check_file_output(self.outfile1, self.correctfile1, reference="correct")
  File "Extra_output.py", line 111, in check_file_output
    out = PT.file_parse_by_word_and_pmagpy_strip(outfile)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 97, in file_parse_by_word_and_pmagpy_strip
    data = file_parse_by_word(a_file)
  File "/Users/nebula/Python/Tests/PmagPy_tests.py", line 71, in file_parse_by_word
    data = open(the_file, 'rU').readlines()

test k15_magic.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Extra_output.py", line 255, in complete_k15_magic_test
    obj = env.run('k15_magic.py', '-WD', directory, '-f', k15_infile, '-Fsa', k15_Fsa, '-Fa', k15_Fa, '-F', k15_F)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test kly4s_magic.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Extra_output.py", line 288, in complete_kly4s_magic_test
    obj = env.run('mv', file_prefix + "er_specimens.txt", file_prefix + "kly4s_er_specimens_new.out") # renames
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test pmag_results_extract.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Extra_output.py", line 311, in complete_pmag_results_extract_test
    obj = env.run('pmag_results_extract.py', '-WD', directory, '-f', 'pmag_results_extract.dat')
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

test orientation_magic.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Extra_output.py", line 336, in complete_orientation_magic_test
    orientation_magic.ex_out_sequence()
  File "Extra_output.py", line 121, in ex_out_sequence
    self.run_program()
  File "Extra_output.py", line 48, in run_program
    obj = env.run(self.name, '-WD', directory, '-f', self.infile, self.tag1, self.outfile1, self.tag2, self.outfile2, self.arg1, stdin=self.stdin)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)


