bootstrap_errors_list:  
test watsonsV.py: Script returned code: 1.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 26, in go_through
    i()
  File "Bootstrap.py", line 142, in complete_watsonsV_test
    output1 = do_watsonsV()
  File "Bootstrap.py", line 130, in do_watsonsV
    obj = env.run("watsonsV.py", "-v", watsonsV_infile, "-f2", watsonsV_infile2, stdin='q') # messed up on purpose, for testing
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 255, in run
    result.assert_no_error(quiet)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 402, in assert_no_error
    "Script returned code: %s" % self.returncode)

programs with errors: ['test watsonsV.py']

