STARTING HERE
CLEANING HOUSE
-
TRYING
 - 
Testing aarm_magic
about to run WD program
('aarm_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'aarm_measurements.txt', '-Fa', 'aarm_magic_anisotropy_new.out', '-Fr', 'aarm_magic_results_new.out', None, 'stdin=None')
stdout: bad_file
bad_file This is not a valid magic_measurements file 

files created: {}
files updated: {}
ran program: aarm_magic.py
checking outfile1 against correctfile1
testing aarm_magic.py: aarm_magic_anisotropy_new.out against reference file: aarm_magic_anisotropy_incorrect.out
NOT expecting an error
parsing file: aarm_magic_anisotropy_new.out
<function complete_aarm_magic_test at 0x4338f0> failed donut
i, ex:  <function complete_aarm_magic_test at 0x4338f0> [Errno 2] No such file or directory: 'aarm_magic_anisotropy_new.out'
type(ex) <type 'exceptions.IOError'>
ex.args (2, 'No such file or directory')
0 <type 'exceptions.IOError'>
1 [Errno 2] No such file or directory: 'aarm_magic_anisotropy_new.out'
2 <traceback object at 0x611800>
TRYING
 - 
Testing atrm_magic.py:
about to run WD program
('atrm_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'atrm_magic_measurements.txt', '-Fa', 'atrm_anisotropy_new.out', '-Fr', 'atrm_results_new.out', None, 'stdin=None')
stdout: bad_file
bad_file This is not a valid magic_measurements file 

files created: {}
files updated: {}
ran program: atrm_magic.py
checking outfile1 against correctfile1
testing atrm_magic.py: atrm_anisotropy_new.out against reference file: atrm_anisotropy_correct.txt
NOT expecting an error
parsing file: atrm_anisotropy_new.out
<function complete_atrm_magic_test at 0x43e3f0> failed donut
i, ex:  <function complete_atrm_magic_test at 0x43e3f0> [Errno 2] No such file or directory: 'atrm_anisotropy_new.out'
type(ex) <type 'exceptions.IOError'>
ex.args (2, 'No such file or directory')
0 <type 'exceptions.IOError'>
1 [Errno 2] No such file or directory: 'atrm_anisotropy_new.out'
2 <traceback object at 0x4369e0>
TRYING
 - 
Testing hysteresis_magic.py
about to run WD program
('hysteresis_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'hysteresis_magic_example.dat', '-F', 'hysteresis_magic_rmag_new.out', None, None, '-P', 'stdin=q')
stdout: 
    NAME
        hysteresis_magic.py

    DESCRIPTION
        calculates hystereis parameters and saves them in rmag_hystereis format file
        makes plots if option selected

    SYNTAX
        hysteresis_magic.py [command line options]

    OPTIONS
        -h prints help message and quits
        -usr USER:   identify user, default is ""
        -f: specify input file, default is agm_measurements.txt
        -fh: specify rmag_hysteresis.txt input file
        -F: specify output file, default is rmag_hysteresis.txt
        -P: do not make the plots
        -spc SPEC: specify specimen name to plot and quit
        -sav save all plots and quit
        -fmt [png,svg,eps,jpg]
    
bad file

files created: {}
files updated: {}
None
hysteresis_magic_remanence_new.out
about to run WD program
('hysteresis_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'hysteresis_magic_example.dat', '-F', 'hysteresis_magic_rmag_new.out', None, 'hysteresis_magic_remanence_new.out', '-P', 'stdin=q')
stdout: 
    NAME
        hysteresis_magic.py

    DESCRIPTION
        calculates hystereis parameters and saves them in rmag_hystereis format file
        makes plots if option selected

    SYNTAX
        hysteresis_magic.py [command line options]

    OPTIONS
        -h prints help message and quits
        -usr USER:   identify user, default is ""
        -f: specify input file, default is agm_measurements.txt
        -fh: specify rmag_hysteresis.txt input file
        -F: specify output file, default is rmag_hysteresis.txt
        -P: do not make the plots
        -spc SPEC: specify specimen name to plot and quit
        -sav save all plots and quit
        -fmt [png,svg,eps,jpg]
    
bad file

files created: {}
files updated: {}
ran program: hysteresis_magic.py
checking outfile1 against correctfile1
testing hysteresis_magic.py: hysteresis_magic_rmag_new.out against reference file: hysteresis_magic_rmag_correct.txt
NOT expecting an error
parsing file: hysteresis_magic_rmag_new.out
<function complete_hysteresis_magic_test at 0x43e470> failed donut
i, ex:  <function complete_hysteresis_magic_test at 0x43e470> [Errno 2] No such file or directory: 'hysteresis_magic_rmag_new.out'
type(ex) <type 'exceptions.IOError'>
ex.args (2, 'No such file or directory')
0 <type 'exceptions.IOError'>
1 [Errno 2] No such file or directory: 'hysteresis_magic_rmag_new.out'
2 <traceback object at 0x436af8>
TRYING
 - 
Testing k15_magic.py
Script result: k15_magic.py -WD /Users/nebula/Python/Basic_input_output -f k15_magic_example.dat -Fsa k15_magic_er_samples_new.out -Fa k15_magic_rmag_anisotropy_new.out -F k15_magic_measurements_new.out
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/Users/nebula/PmagPy/k15_magic.py", line 331, in <module>
    main() 
  File "/Users/nebula/PmagPy/k15_magic.py", line 122, in main
    input=open(k15file,'rU')
IOError: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/k15_magic_example.dat'

<function complete_k15_magic_test at 0x43e4b0> failed donut
i, ex:  <function complete_k15_magic_test at 0x43e4b0> Script returned code: 1
type(ex) <type 'exceptions.AssertionError'>
ex.args ('Script returned code: 1',)
0 <type 'exceptions.AssertionError'>
1 Script returned code: 1
2 <traceback object at 0x436b48>
TRYING
 - 
Testing kly4s_magic.py
Error opening file:  /Users/nebula/Python/Basic_input_output/kly4s_magic_example.dat

Script result: mv /Users/nebula/Python/Basic_input_output/er_specimens.txt /Users/nebula/Python/Basic_input_output/kly4s_er_specimens_new.out
  return code: 1
-- stderr: --------------------
mv: rename /Users/nebula/Python/Basic_input_output/er_specimens.txt to /Users/nebula/Python/Basic_input_output/kly4s_er_specimens_new.out: No such file or directory

<function complete_kly4s_magic_test at 0x43e4f0> failed donut
i, ex:  <function complete_kly4s_magic_test at 0x43e4f0> Script returned code: 1
type(ex) <type 'exceptions.AssertionError'>
ex.args ('Script returned code: 1',)
0 <type 'exceptions.AssertionError'>
1 Script returned code: 1
2 <traceback object at 0x74d378>
TRYING
 - 
Testing pmag_results_extract.py
Script result: pmag_results_extract.py -WD /Users/nebula/Python/Basic_input_output -f pmag_results_extract.dat
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/Users/nebula/PmagPy/pmag_results_extract.py", line 287, in <module>
    main()
  File "/Users/nebula/PmagPy/pmag_results_extract.py", line 72, in main
    f=open(outfile,'w')
IOError: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/Directions.txt'

<function complete_pmag_results_extract_test at 0x43e530> failed donut
i, ex:  <function complete_pmag_results_extract_test at 0x43e530> Script returned code: 1
type(ex) <type 'exceptions.AssertionError'>
ex.args ('Script returned code: 1',)
0 <type 'exceptions.AssertionError'>
1 Script returned code: 1
2 <traceback object at 0x74d3f0>
TRYING
 - 
Testing orientation_magic.py
about to run WD program
('orientation_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'orientation_magic_exa.txt', '-Fsi', 'orientation_magic_er_sites_new.out', '-Fsa', 'orientation_magic_er_samples_new.out', None, 'stdin=None')
Script result: orientation_magic.py -WD /Users/nebula/Python/Basic_input_output -f orientation_magic_exa.txt -Fsi orientation_magic_er_sites_new.out -Fsa orientation_magic_er_samples_new.out None
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/Users/nebula/PmagPy/orientation_magic.py", line 543, in <module>
    main()
  File "/Users/nebula/PmagPy/orientation_magic.py", line 536, in main
    pmag.magic_write(samp_file,SampsOut,"er_samples")
  File "/Users/nebula/PmagPy/pmag.py", line 987, in magic_write
    pmag_out=open(ofile,'w')
IOError: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/orientation_magic_er_samples_new.out'

-- stdout: --------------------
saving data...

<function complete_orientation_magic_test at 0x43e570> failed donut
i, ex:  <function complete_orientation_magic_test at 0x43e570> Script returned code: 1
type(ex) <type 'exceptions.AssertionError'>
ex.args ('Script returned code: 1',)
0 <type 'exceptions.AssertionError'>
1 Script returned code: 1
2 <traceback object at 0x74d490>
messed up programs ['testing aarm_magic.py', 'test atrm_magic.py', 'test hysteresis_magic.py', 'test k15_magic.py', 'test kly4s_magic.py', 'test pmag_results_extract.py', 'test orientation_magic.py']
total errors found: 7
THESE ONES ARE BROKEN  ['testing aarm_magic.py', 'test atrm_magic.py', 'test hysteresis_magic.py', 'test k15_magic.py', 'test kly4s_magic.py', 'test pmag_results_extract.py', 'test orientation_magic.py']
redo me list [<function complete_aarm_magic_test at 0x4338f0>, <function complete_atrm_magic_test at 0x43e3f0>, <function complete_hysteresis_magic_test at 0x43e470>, <function complete_k15_magic_test at 0x43e4b0>, <function complete_kly4s_magic_test at 0x43e4f0>, <function complete_pmag_results_extract_test at 0x43e530>, <function complete_orientation_magic_test at 0x43e570>]
rhino
testing aarm_magic.py
Testing aarm_magic
about to run WD program
('aarm_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'aarm_measurements.txt', '-Fa', 'aarm_magic_anisotropy_new.out', '-Fr', 'aarm_magic_results_new.out', None, 'stdin=None')
stdout: bad_file
bad_file This is not a valid magic_measurements file 

files created: {}
files updated: {}
ran program: aarm_magic.py
checking outfile1 against correctfile1
testing aarm_magic.py: aarm_magic_anisotropy_new.out against reference file: aarm_magic_anisotropy_incorrect.out
NOT expecting an error
parsing file: aarm_magic_anisotropy_new.out
testing aarm_magic.py raised error: [Errno 2] No such file or directory: 'aarm_magic_anisotropy_new.out'
-----------
-----------
test atrm_magic.py
Testing atrm_magic.py:
about to run WD program
('atrm_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'atrm_magic_measurements.txt', '-Fa', 'atrm_anisotropy_new.out', '-Fr', 'atrm_results_new.out', None, 'stdin=None')
stdout: bad_file
bad_file This is not a valid magic_measurements file 

files created: {}
files updated: {}
ran program: atrm_magic.py
checking outfile1 against correctfile1
testing atrm_magic.py: atrm_anisotropy_new.out against reference file: atrm_anisotropy_correct.txt
NOT expecting an error
parsing file: atrm_anisotropy_new.out
test atrm_magic.py raised error: [Errno 2] No such file or directory: 'atrm_anisotropy_new.out'
-----------
-----------
test hysteresis_magic.py
Testing hysteresis_magic.py
about to run WD program
('hysteresis_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'hysteresis_magic_example.dat', '-F', 'hysteresis_magic_rmag_new.out', None, None, '-P', 'stdin=q')
stdout: 
    NAME
        hysteresis_magic.py

    DESCRIPTION
        calculates hystereis parameters and saves them in rmag_hystereis format file
        makes plots if option selected

    SYNTAX
        hysteresis_magic.py [command line options]

    OPTIONS
        -h prints help message and quits
        -usr USER:   identify user, default is ""
        -f: specify input file, default is agm_measurements.txt
        -fh: specify rmag_hysteresis.txt input file
        -F: specify output file, default is rmag_hysteresis.txt
        -P: do not make the plots
        -spc SPEC: specify specimen name to plot and quit
        -sav save all plots and quit
        -fmt [png,svg,eps,jpg]
    
bad file

files created: {}
files updated: {}
None
hysteresis_magic_remanence_new.out
about to run WD program
('hysteresis_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'hysteresis_magic_example.dat', '-F', 'hysteresis_magic_rmag_new.out', None, 'hysteresis_magic_remanence_new.out', '-P', 'stdin=q')
stdout: 
    NAME
        hysteresis_magic.py

    DESCRIPTION
        calculates hystereis parameters and saves them in rmag_hystereis format file
        makes plots if option selected

    SYNTAX
        hysteresis_magic.py [command line options]

    OPTIONS
        -h prints help message and quits
        -usr USER:   identify user, default is ""
        -f: specify input file, default is agm_measurements.txt
        -fh: specify rmag_hysteresis.txt input file
        -F: specify output file, default is rmag_hysteresis.txt
        -P: do not make the plots
        -spc SPEC: specify specimen name to plot and quit
        -sav save all plots and quit
        -fmt [png,svg,eps,jpg]
    
bad file

files created: {}
files updated: {}
ran program: hysteresis_magic.py
checking outfile1 against correctfile1
testing hysteresis_magic.py: hysteresis_magic_rmag_new.out against reference file: hysteresis_magic_rmag_correct.txt
NOT expecting an error
parsing file: hysteresis_magic_rmag_new.out
test hysteresis_magic.py raised error: [Errno 2] No such file or directory: 'hysteresis_magic_rmag_new.out'
-----------
-----------
test k15_magic.py
Testing k15_magic.py
Script result: k15_magic.py -WD /Users/nebula/Python/Basic_input_output -f k15_magic_example.dat -Fsa k15_magic_er_samples_new.out -Fa k15_magic_rmag_anisotropy_new.out -F k15_magic_measurements_new.out
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/Users/nebula/PmagPy/k15_magic.py", line 331, in <module>
    main() 
  File "/Users/nebula/PmagPy/k15_magic.py", line 122, in main
    input=open(k15file,'rU')
IOError: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/k15_magic_example.dat'

test k15_magic.py raised error: Script returned code: 1
-----------
-----------
test kly4s_magic.py
Testing kly4s_magic.py
Error opening file:  /Users/nebula/Python/Basic_input_output/kly4s_magic_example.dat

Script result: mv /Users/nebula/Python/Basic_input_output/er_specimens.txt /Users/nebula/Python/Basic_input_output/kly4s_er_specimens_new.out
  return code: 1
-- stderr: --------------------
mv: rename /Users/nebula/Python/Basic_input_output/er_specimens.txt to /Users/nebula/Python/Basic_input_output/kly4s_er_specimens_new.out: No such file or directory

test kly4s_magic.py raised error: Script returned code: 1
-----------
-----------
test pmag_results_extract.py
Testing pmag_results_extract.py
Script result: pmag_results_extract.py -WD /Users/nebula/Python/Basic_input_output -f pmag_results_extract.dat
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/Users/nebula/PmagPy/pmag_results_extract.py", line 287, in <module>
    main()
  File "/Users/nebula/PmagPy/pmag_results_extract.py", line 72, in main
    f=open(outfile,'w')
IOError: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/Directions.txt'

test pmag_results_extract.py raised error: Script returned code: 1
-----------
-----------
test orientation_magic.py
Testing orientation_magic.py
about to run WD program
('orientation_magic.py', '-WD', '/Users/nebula/Python/Basic_input_output', '-f', 'orientation_magic_exa.txt', '-Fsi', 'orientation_magic_er_sites_new.out', '-Fsa', 'orientation_magic_er_samples_new.out', None, 'stdin=None')
Script result: orientation_magic.py -WD /Users/nebula/Python/Basic_input_output -f orientation_magic_exa.txt -Fsi orientation_magic_er_sites_new.out -Fsa orientation_magic_er_samples_new.out None
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/Users/nebula/PmagPy/orientation_magic.py", line 543, in <module>
    main()
  File "/Users/nebula/PmagPy/orientation_magic.py", line 536, in main
    pmag.magic_write(samp_file,SampsOut,"er_samples")
  File "/Users/nebula/PmagPy/pmag.py", line 987, in magic_write
    pmag_out=open(ofile,'w')
IOError: [Errno 2] No such file or directory: '/Users/nebula/Python/Basic_input_output/orientation_magic_er_samples_new.out'

-- stdout: --------------------
saving data...

test orientation_magic.py raised error: Script returned code: 1
-----------
-----------
finished with Extra_output.py testing and re-testing
