'random_errors_list:  
test gaussian.py: global name 'o1' is not defined.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Random.py", line 186, in complete_gaussian_test
    print("output 1 length: ", o1)

test fisher.py: fisher.py is producing the wrong amount of output.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Random.py", line 36, in complete_fisher_test
    raise NameError("fisher.py is producing the wrong amount of output")

test tk03.py: cannot concatenate 'str' and 'list' objects.  
Traceback below: 
  File "/Users/nebula/Python/Tests/error_logging.py", line 28, in go_through
    i()
  File "Random.py", line 120, in complete_tk03_test
    print "output1: " + out1


